### ISSUE TITLE
unable to determine number of filtered record from batch

### ISSUE THREAD

**Issue by chazo** [EasyBatch/easybatch-framework#170]
While performing BatchRecord Processing, even if some individual records are filtered out, the job report shows 0% filtered. 
Also, currently the BatchRecord is treated as one record, there must be a way to show individual record count and individual filtered count in the job report.

**Comment by benas** [comment]
Yes, in batch mode all metrics are per batch and not per record, because each batch of records is treated [as a unit](https://speakerdeck.com/benas/easy-batch?slide=15)

Easy Batch reporting should be more precise in this case and give detailed information per batch and per record too. 

I'll plan this improvement for the next release.
Keep tuned

**Comment by chazo** [comment]
Instead of returning null for the filter, perhaps we need to set a flag in the header to filter. This information can be used to update the job report before excluding it for the next thing in the chain. This will also be useful for the batchfilter to determine which individual record was filtered.

________________________________

**Comment by benas** [comment]
Yes, good idea. The record header can be used for this use case. I'll consider your suggestion in the implementation of this improvement.

Thank you

**Comment by benas** [comment]
Hi @chazo 

> While performing BatchRecord Processing, even if some individual records are filtered out, the job report shows 0% filtered. 

How this is possible? When I register a filter in batch mode, the whole batch is filtered, not indivudal records. How did you managed to filter individual records from a batch?

Kind regards
Mahmoud

**Comment by chazo** [comment]
please find my filter below. Not sure if this is the intended way to use it
```java
final class ExistingRecordBatchFilter implements RecordFilter<Batch> {


	@Override
	public Batch processRecord(Batch record) {
		final List<Record<EnrollmentInputData>> records = (List)record.getPayload();
		int chunkSize = records.size();
		if(chunkSize==0){
			return record;
		}
		records.removeIf(r->r.getPayload().getSomeString()=="filterMe");

		return record;
	}
}
```

**Comment by benas** [comment]
Thank you for the quick reply.

Before tackling the issue, I want to give you a hint about your filter. You can actually use the `BatchFilter` with a delegate `RecordFilter`. In your case:

```java
new BatchFilter(new GrepFilter("filterMe")); // or another record filter according to your requirement
```

That said, you can use the Batch filter this way, to filter some records from the batch. It is intended to be used like this since Easy Batch allows you to do it through the `BatchFilter` along with a delegate `RecordFilter`.  Now the issue comes with reporting. You are expecting to see statistics per record even if you decided to use batch processing right? Here is an example:

```java
String datasource = "#header\nfoo\nbar\n#footer";

Job job = JobBuilder.aNewJob()
        .reader(new StringBatchReader(datasource, 2))
        .filter(new BatchFilter(new StartWithStringRecordFilter("#")))
        .build();

JobReport jobReport = JobExecutor.execute(job);
System.out.println(jobReport);

// prints:
Total count = 2
Skipped count = 0 (0.0%)
Filtered count = 0 (0.0%)
Error count = 0 (0.0%)
Success count = 2 (100.0%)
```

These stats are per batch since the job is working in batch mode. You are expecting this:

```
Total count = 4
Skipped count = 0 (0.0%)
Filtered count = 2 (50.0%)
Error count = 0 (0.0%)
Success count = 2 (50.0%)
```

Is this the problem?

Cheers
Mahmoud

**Comment by chazo** [comment]
Mahmoud,
I'm looking to filter in a batch way as well. My real use case runs a query against the database with values from the batch to find entries that are already present and remove them from the batch. So if my chunk size was a 100, in the example you provided I would run the query a 100 times vs once if I had an in clause with 100 bindings.
Thanks,
Chandru

**Comment by benas** [comment]
> My real use case runs a query against the database with values from the batch to find entries that are already present and remove them from the batch

I see your use case, I guessed that from the name of your class :smile: 

The example I gave was just to reproduce to reporting issue your are pointing out, not a suggestion for your filter. 

In my previous comment, I said:

> in batch mode all metrics are per batch and not per record, because each batch of records is treated as a unit and hence the reporting should be coherent.

Since easy batch allows to filter records from a batch, the "per batch reporting" is indeed wrong or at least ambiguous. I think the reporting should be per record regardless if the if the job is executed in batch or record mode. What do you think?

In the previous example, `#header` and `#footer` records will be filtered, hence the report should be:

```
Total count = 4
Skipped count = 0 (0.0%)
Filtered count = 2 (50.0%)
Error count = 0 (0.0%)
Success count = 2 (50.0%)
```

Do you agree?

**Comment by benas** [comment]
Hi,

I'm struggling to find a clean way to fix this reporting problem. The problem is deeper that just a reporting bug. I must admit there are some design issues with the current API and implementation ( explained in #211 ).

I was busy the last few days working on the next major version ( which you can try out already with version 5.0.0-SNAPSHOT). This new version should fix the problem by design: regardless to the batch size, the reporting is always consistent.

I'm going to update the documentation asap, but if you are curious and can give your feedback in the meanwhile, I would be grateful to you :smile: 

Kind regards
Mahmoud

**Comment by benas** [comment]
As discussed previously, the reported issue simply disappears with v5. This new version fixes the problem by design: reading a batch and then filtering some records from a batch is no more possible. Records are always read/processed one item at time and then written in batches. Hence, regardless of the batch size, the reporting is always consistent.
