### ISSUE TITLE
Write delimited file without NULL values obtained from the data source(database)

### ISSUE THREAD

**Issue by archenroot** [EasyBatch/easybatch-framework#181]
#103 
#104 

Hi,

similar issue as previously reported with Oracle database tables on input. There can be multiple behaviors behind the scene when NULL field on input:
- if target database type -> stay NULL - 
- if target file -> can be switch/flag driven -> 

1. default is empty string ""
2. leave null
3. completely remove the column from export (cannot imagine scenario, but in general why not :dancer: )

This behavior can differ across different target technology endpoint.

Ladislav

**Comment by benas** [comment]
Hi,

In issues 103 and 104 the question is about mapping data from the input record to a target object.

In this issue you are asking about record writers/marshallers, right?

> if target database type -> stay NULL -

Here you can use a JDBC writer with a `PreparedStatement` and you can implement your strategy according to how your target database handle NULL values. You can find an example [here](http://www.easybatch.org/tutorials/loading-data.html). In this case, since it is the user that provides the writing logic, Easy Batch can not help.

> if target file -> can be switch/flag driven

Here we speak about record marshallers (CSV, JSON, XML, etc..). We have a domain object and we would like to marshal it to CSV. Now the question is: when a particular field is null, how does Easy Batch would handle it:

1. default is empty string ""
2. leave null
3. completely remove the column from export (cannot imagine scenario, but in general why not :dancer: )

I'm a correct? Just to be sure we are on the same page :smile: 

Currently, there are two record marshallers that can write a bean to CSV: `DelimitedRecordMarshaller` and `ApacheCommonCsvRecordMarshaller`. These guys can be configured with a `RecordFieldExtractor` that has been specifically designed for such use cases (see issue #117 ). You can provide a custom implementation of this interface with one of the strategies you mentioned above.

Hope this helps.
Kind regards
Mahmoud

**Comment by archenroot** [comment]
Brilliant, we are on the same page it looks like. It looks clear, so I can implement new Marshaller for  RecordMarshaller<GenericRecord,StringRecord> interface. Hot to name it? What about DelimitedNoNullRecordMarshaller?

**Comment by benas** [comment]
Hi,

I think we can still use the current `DelimlitedRecordMapper` with a custom `RecordFieldExtractor` to implement our "Null" marshalling strategy. Let's see a quick example, here is the domain object :

```java
public class Foo {
   private int id;   
   private String name;
   // constructors, getters and setters
}
```

* The Null to Empty Strategy : when a field is null we want to marshall an empty string instead of the default "null" literal

```java
class NullToEmptyFieldMarshallingStrategy implements RecordFieldExtractor {
    @Override
    public Iterable<Object> extractFields(Object record) throws RecordFieldExtractionException {
        Foo foo = (Foo) record;
        List<Object> fields = new ArrayList<>();
        fields.add(foo.getId());
        fields.add(foo.getName() == null ? "" : foo.getName());
        return fields;
    }
}
```

* The Null to Absent Strategy : when a field is null we want to omit the field from being marshalled

```java
class NullToAbsentFieldMarshallingStrategy implements RecordFieldExtractor {
    @Override
    public Iterable<Object> extractFields(Object record) throws RecordFieldExtractionException {
        Foo foo = (Foo) record;
        List<Object> fields = new ArrayList<>();
        fields.add(foo.getId());
        if (foo.getName() != null) {
            fields.add(foo.getName());
        }
        return fields;
    }
}
```

And here are the (passing) test cases:

```java
import java.util.ArrayList;
import java.util.List;
import org.assertj.core.api.Assertions;
import org.easybatch.core.field.RecordFieldExtractionException;
import org.easybatch.core.field.RecordFieldExtractor;
import org.easybatch.core.record.GenericRecord;
import org.easybatch.core.record.StringRecord;
import org.junit.Test;

public class RecordMarshallingTest {

    private Foo foo;

    private DelimitedRecordMarshaller delimitedRecordMarshaller;

    @Test
    public void testRecordMarshalling() throws Exception {
        foo = new Foo(1, "foo");
        delimitedRecordMarshaller = new DelimitedRecordMarshaller(Foo.class);
        StringRecord stringRecord = delimitedRecordMarshaller.processRecord(new GenericRecord<>(null, foo));
        Assertions.assertThat(stringRecord.getPayload()).isEqualTo("\"1\",\"foo\"");
    }

    @Test
    public void testRecordMarshallingWithDefaultStrategy() throws Exception {
        foo = new Foo(1, null);
        delimitedRecordMarshaller = new DelimitedRecordMarshaller(Foo.class);
        StringRecord stringRecord = delimitedRecordMarshaller.processRecord(new GenericRecord<>(null, foo));
        Assertions.assertThat(stringRecord.getPayload()).isEqualTo("\"1\",\"null\"");
    }

    @Test
    public void whenFieldIsNull_thenShouldMarshallEmptyString() throws Exception {
        foo = new Foo(1, null);
        delimitedRecordMarshaller = new DelimitedRecordMarshaller(new NullToEmptyFieldMarshallingStrategy(), ";", "'");
        StringRecord stringRecord = delimitedRecordMarshaller.processRecord(new GenericRecord<>(null, foo));
        Assertions.assertThat(stringRecord.getPayload()).isEqualTo("'1';''");
    }

    @Test
    public void whenFieldIsNull_thenShouldNotMarshallTheField() throws Exception {
        foo = new Foo(1, null);
        delimitedRecordMarshaller = new DelimitedRecordMarshaller(new NullToAbsentFieldMarshallingStrategy(), ";", "'");
        StringRecord stringRecord = delimitedRecordMarshaller.processRecord(new GenericRecord<>(null, foo));
        Assertions.assertThat(stringRecord.getPayload()).isEqualTo("'1'");
    }

}
```

As you can see, the `RecordFieldExtractor` is a strategy interface that allows us to provide custom marshalling behavior. That said , we can of course create another implementation of the `RecordMarshaller` interface called `DelimitedNoNullRecordMarshaller`. But in this case, we would create another marshaller for each requirement. All strategies will end up built-in in the framework and this is not the goal. Do you see the point?

Hope this example helps to understand the design goal behind the `RecordFieldExtractor`.

Best regards
Mahmoud

**Comment by archenroot** [comment]
I see now. Thanks for comprehensive explanation, I also agree that create the delimiter is not the good way. I overlooked that constructor in Marschaller which can absorb RecordFieldExtractor interface implementation.

You did the implementation with test cases for me :+1: 

Many thanks.

Ladislav

**Comment by benas** [comment]
No problem, I'm always glad to help.

Kind regards
Mahmoud
