### ISSUE TITLE
Hibernate Record Reader & Group By not working as expected

### ISSUE THREAD

**Issue by denisbetsi** [EasyBatch/easybatch-framework#182]
A simple
``
HibernateBatchReader<Post_tags>(10, sessionFactory, "FROM post_tags") 
``
Works as expected

Attempts to use a group by breaks it

``
HibernateBatchReader<Post_tags>(10, sessionFactory, "select max(id) as id, tableName, tag,ts,sum(wordCount) as wordCount,sum(totalWordCount) as totalWordCount, count(*) as docCount from Post_tags group by tableName, tag, ts") 

``

Looking at HibernateRecordReader I found

``
Query hibernateQuery = session.createQuery(query);
``

What fixes is having it queried like

``
session.createSQLQuery(query).addEntity("Post_tags", Post_tags.class)
``

That forces Hibernate to treat this query as an entity vs unmapped objects which in return break RecordReader

**Comment by benas** [comment]
Hi,

The `HibernateRecordReader` and `HibernateBatchReader` expect a HQL query (see [javadoc](http://www.easybatch.org/api/org/easybatch/extensions/hibernate/HibernateBatchReader.html#constructor_detail)) and not a native SQL query.

> Attempts to use a group by breaks it

It looks like your query containing the 'group by' is a native SQL. Have you tried to use a 'group by' with a HQL query? This should work fine.

Native SQL queries with hibernate readers are not supported. You can use the `JdbcRecordReader` to execute plain SQL along with the `JdbcRecordMapper` to map rows to your domain object instances.

Please let me know it you have any issue with a 'group by' in a HQL query.

Hope this helps
Mahmoud

**Comment by denisbetsi** [comment]
The issue is I couldn't find JdbcBatchReader. Is there a Jdbc Batch Reader?

**Comment by benas** [comment]
Hi,

There is no such a `JdbcBatchReader`. The reason is that the JDBC API does not provide an abstraction for a *single* row. The `ResultSet` represents a whole table with a cursor. In Easy Batch, a `JdbcRecord` holds a `ResultSet` with the cursor pointing to the current row (the user does not iterate over the ResultSet, Easy Batch handles it).

That said, representing a `Batch` of `JdbcRecord`s makes no sense, and that's why there is no a `JdbcBatchReader`. This is more a design decision that a missing feature.

This is not the case with JPA or Hibernate, since rows are directly mapped to domain objects. We can get a representation of a single row and hence read them in batches.

Kind regards
Mahmoud

**Comment by denisbetsi** [comment]
Sounds good. Thank you.
