### ISSUE TITLE
Support @DisallowConcurrentExecution for easybatch quartz extension

### ISSUE THREAD

**Issue by niyue** [EasyBatch/easybatch-framework#201]
Some scheduled jobs are not expected to be run concurrently, for example, a job to collect data with concurrently running instances may result duplication of data. 

In quartz the scheduler, it allows users to use annotations like @DisallowConcurrentExecution for Job class to disable concurrent execution. However, in easybatch's quartz extension doesn't expose this functionality. 

Is there any chance we could support this? Thanks.

I read the source code of easybatch's quartz extension and quartz itself, and found there are different ways to do this, but I am not certain which one is the best. I am happy to send a PR for this, but please shed me some light on the ideal solution for this issue. Thanks.

Some related links:
- http://www.quartz-scheduler.org/documentation/quartz-2.x/examples/Example4
- http://www.quartz-scheduler.net/documentation/quartz-2.x/tutorial/more-about-jobs.html

**Comment by benas** [comment]
Hi, thank you for opening this issue.

> Some scheduled jobs are not expected to be run concurrently

Do you think the framework can help here? Why not simply schedule them to not run concurrently?

> there are different ways to do this, but I am not certain which one is the best.

Could you please give an example of you would do this in easy batch? I mean how do you want/expect the feature to be used in easy batch.

Kind regards
Mahmoud

**Comment by yangguo981** [comment]
@benas what do you mean "simply schedule them to not run concurrently?"
My case is, a job is scheduled every 10 minutes, then update DB.
Mostly, it runs for seconds, but sometimes over 1 hour(Due to huge calculation).
How schedule to not run concurrently?

**Comment by benas** [comment]
Sorry, let me rectify my question:  Why not <strike>simply</strike> try to schedule them to not run concurrently? :smile: But I know, this is not always possible, especially when an execution exceeds the expected duration. My idea was to specify enough time between executions to prevent them from running concurrently. This is what I meant.

> I read the source code of easybatch's quartz extension and quartz itself, and found there are different ways to do this, but I am not certain which one is the best

Could you please tell me what are the different ways? We will try to find the best one.

Is there a way to disallow concurrent executions programmatically in quartz (without annotation or extending/implementing a class/interface)? If this is the case, probably add a parameter in `schedule*` methods to disallow concurrent executions:

```java
jobScheduler.scheduleAtWithInterval(job1, now, 10, true);
```

The 4th parameter is disallow concurrent execution.

Any other ideas are welcome!
Many thanks upfront

**Comment by niyue** [comment]
@benas Sorry for the late reply. I missed the initial response from you. 

> Is there a way to disallow concurrent executions programmatically in quartz (without annotation or extending/implementing a class/interface)? 
I don't find such a way yet. Quartz internally uses class introspection to detect if the annotation is added to the `Job`:
https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/java/org/quartz/impl/JobDetailImpl.java#L386-L389

In easybatch's quartz extension, the `Job` class is hardcoded and API consumer has no way to use their own Job implementation. Right now, I have to use JavaAssist to programmatically add the @DisallowConcurrentExecution annotation to the `Job` class to achieve this.

Additionally, I would like to control some policy to instruct how quartz should act when certain job is delayed for a long time (this could be a separated issue but may be solved together with this issue). These policies are specified via API of SimpleScheduleBuilder, but it is not accessible via current easybatch quartz extension API yet.
https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/java/org/quartz/SimpleScheduleBuilder.java#L400-L402

I think EasyBatch's Quartz extension should not be designed to expose all APIs from Quartz, but maybe there is some chance we could find a balance to make it more flexible to extend. 

Thanks a lot for the help.

**Comment by benas** [comment]
> In easybatch's quartz extension, the Job class is hardcoded

No, it is not hard coded, it is package private *by design*. We don't want users of the easybatch-quartz module to deal with quartz APIs, this is the whole purpose of the module.

> API consumer has no way to use their own Job implementation.

The `JobScheduler` API is designed to schedule easy batch jobs, not quartz jobs. Behind the scene, easy batch jobs are wrapped in quartz jobs to be scheduled by quartz. Now, if quartz does not allow to add a feature programmatically, it is quartz's problem. 

> Right now, I have to use JavaAssist to programmatically add the @DisallowConcurrentExecution annotation to the Job class to achieve this.

Of course, when the only way to add a feature is by adding an annotation, you have to do these hacks.
Quartz should give a programmatic way to disable concurrent executions (in addition to annotation), something like:

```
SimpleScheduleBuilder scheduleBuilder = SimpleScheduleBuilder.simpleSchedule()
     .withIntervalInSeconds(interval)
     .repeatForever()
     .disallowConcurrentExecutions(); // for example
```

This way, as a user of quartz, I can enable/disable the feature without adding an annotation.

> Additionally, I would like to control some policy to instruct how quartz should act when certain job is delayed for a long time (this could be a separated issue but may be solved together with this issue). These policies are specified via API of SimpleScheduleBuilder, but it is not accessible via current easybatch quartz extension API yet.

Great! here I agree :smile: Since it is possible through the API, we can expose them via the `JobScheduler`, no problem. Please open a separate issue for that and I'll plan it for next release.

> I think EasyBatch's Quartz extension should not be designed to expose all APIs from Quartz, but maybe there is some chance we could find a balance to make it more flexible to extend.

Sure, let me know what other features you need and we can discuss to add them.

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi @niyue

I wish you a happy new year!

In regards to this issue, there are two points:

* `@DisallowConcurrentExecution`: as discussed, since quartz does not provide this feature programmatically, I don't want to add hacks with byte code manipulation to support it in easy batch. Sorry about that, hope you understand this decision.

* As requested, I've created an issue ( see #260 ) to add the ability to control policies on how quartz should act when certain job is delayed for a long time. Since quartz allows this programmatically, it's fine to add to the extension. Please consider to add more details in #260.

Kind regards
Mahmoud
