### ISSUE TITLE
Problem with Xml special characters

### ISSUE THREAD

**Issue by benas** [EasyBatch/easybatch-framework#67]
The `XmlRecordReader` escapes XML content when reading a valid XML document. Or, if the payload of the `XmlRecord` is escaped, it becomes invalid, which leads to a `RecordMappingException` when trying to map the `XmlRecord` to a domain object. Here is an example:

```xml
<website name="google" url="http://www.google.com?query=test&amp;sort=asc"/>
```

The XmlRecordReader returns the following as payload:

```xml
<website name="google" url="http://www.google.com?query=test&sort=asc"/>
```

This is actually invalid XML content! So the reader should keep characters escaped in order to the `XmlRecordMapper` correctly map the records to domain objects.

**Comment by lsoltero35** [comment]
I am having this problem with current release [5.0.0](https://github.com/EasyBatch/easybatch-framework/milestone/10) in which it happens as described in issue, however what is changed is that the text containing the `&amp;` tag is the char data instead of an attribute. 

A sample would be like this: 
`<website name="google">http://www.google.com?query=test&amp;sort=asc</website>`

I tested and same code I have can handle the `&amp;` as attribute but not as char data.

**Comment by benas** [comment]
Hi, 

Thank you for reporting this.
I'll see if the fix can be applied to char data too.
Will keep you informed when the fix is published.

You are welcome to contribute a fix if you want!

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi @lsoltero35 

Thank you for reporting this issue. I do confirm, the xml reader alters the payload by escaping special characters in the tag's body. I've created a new issue for this issue ( see #277 ) and fixed the problem.

The fix will be included in the upcoming release.
Stay tuned!

Kind regards
Mahmoud

**Comment by lsoltero35** [comment]
Thank you, I will check it there and let you know.
