### ISSUE TITLE
Add chunk processing support

### ISSUE THREAD

**Issue by benas** [EasyBatch/easybatch-framework#87]
Add a `MultiRecordReader` that reads records in chunks. This reader should delegate record reading to an existing reader. A new concept of `MutliRecord` will be introduced to represent a chunk of records. Example:

```java
MultiRecordReader multiRecordReader = 
                           new MultiRecordReader(10, new FlatFileRecordReader(file));
```

This will read 10 flat records at a time using a `FlatFileRecordReader`.

**Comment by gs-spadmanabhan** [comment]
Looking forward for this.

**Comment by benas** [comment]
Hi Sunand, Hope your are doing well!

I've added support for chunk processing through the `MultiRecord` abstraction. Multi-records represent a chunk of records read by a `MultiRecordReader` (which delegates record reading to a regular `RecordReader`).

I've already added support for [flat files](https://github.com/EasyBatch/easybatch-framework/blob/master/easybatch-flatfile/src/test/java/org/easybatch/flatfile/FlatFileMultiRecordReaderTest.java), [strings](https://github.com/EasyBatch/easybatch-framework/blob/master/easybatch-core/src/test/java/org/easybatch/core/reader/StringMultiRecordReaderTest.java) and [iterable](https://github.com/EasyBatch/easybatch-framework/blob/master/easybatch-core/src/test/java/org/easybatch/core/reader/IterableMultiRecordReaderTest.java) data sources.
Support for other data sources is in the pipe ..

Do not hesitate to [try it out](https://github.com/EasyBatch/easybatch-framework#current-version) with version 3.1.0-SNAPSHOT. Looking forward for your feedback :-)

Cheers
Mahmoud

**Comment by gs-spadmanabhan** [comment]
Hi Mahmoud,

I checked out the Json Multi Record Reader and MongoDB Multi Record Reader (and +1 for this). One quick suggestion will be in the report.getTotalRecords() method I would expect total number of records irrespective of the chunk size. Whereas the report.getBatchResult() is perfect where I get the chunked record list.

Also one more possibility I can think of (since chunking came in to picture) would be something like MongoDB Multi Record Writer, this will be extremely handy in case of bulk writes.

- Sunand

**Comment by benas** [comment]
Hi Sunand,

Thank you for trying out! As requested, I've added a new `MongoDBMultiRecordWriter` to support bulk inserts. [here](https://github.com/EasyBatch/easybatch-framework/blob/master/easybatch-integration/easybatch-mongodb/src/test/java/org/easybatch/integration/mongodb/MongoDBMultiRecordWriterTest.java#L98) is an example. What do you think?

In regards to the `report.getTotalRecords()`, this method cannot return the total records irrespective to the chunk size because the API will be inconsistent in this case. What if the user decide to skip or filter some records? The engine will skip/filter one MultiRecord in the process but actually there should be X skipped/filtered records in the report. The other use case is when the user decide to map a MultiRecord to a domain object, in this case, we should count one record for the domain object and not X records of the MultiRecord. Do you see the trick? The internal workflow is record wise and the new `MultiRecord` abstraction should not break the API consistency.

Final note, I've added a new "writer" method in the builder API. This makes the intention of the processor more explicit:

```java
List<String> dataSource = Arrays.asList("foo", "bar", "baz");

aNewEngine()
   .reader(new IterableRecordReader(dataSource))
   .writer(new StandardOutputRecordWriter())
   .build().call();
``` 

Kind regards,
Mahmoud

**Comment by gs-spadmanabhan** [comment]
Hi Mahmoud,

Bulk Write will really help in ETL scenarios thank you for adding this. 

Reader, Mapper, Writer very clean way of segregating things.

Coming to ```report.getTotalRecords()```, In case of skipped records or filtered records should it not show the actual records skipped instead of number of MultiRecord? Since chunking is a feature where as report should have actual information isn't it? Something like a drill down of one MultiRecord. But I got your point on the API consistency, just placing another perspective.

Noticed one more thing while debugging the test class, Engine class is an extension of Report class right (```Engine extends Callable<Report>```)? In the Report class we have a transient variable ```private transient Engine engine;```. Any reason why such a reference done?

- Sunand

**Comment by benas** [comment]
Hi Sunand,

Thank you for the quick review!

> Reader, Mapper, Writer very clean way of segregating things

In fact, with the introduction of writers, the purpose of each component is now more explicit (it is better to write `.writer(myFileWriter)` than `.processor(myFileWriter)`. I've added a new ETL tutorial [here](https://github.com/EasyBatch/easybatch-tutorials/blob/next-version/src/main/java/org/easybatch/tutorials/intermediate/csv2xml/Launcher.java) with an example of each component. I hope this will be easier for users to read and understand the purpose of each component.

>In the Report class we have a transient variable private transient Engine engine;. Any reason why such a reference done?

Good point! The goal was to get the name and execution Id of the engine that produced the report but, in fact, there is no need to reference the whole instance. I've [removed](https://github.com/EasyBatch/easybatch-framework/commit/694d54884d55dc4c7a8db5410fa58f7464e01689) it by setting the engine name and execution Id at the job initialization phase. I've certainly done this late after midnight :-).

Best regards
Mahmoud

**Comment by gs-spadmanabhan** [comment]
Awesome, hope this change doesn't affect people using previous releases.

- Sunand
